GET http://localhost:3001/



###
POST http://localhost:3001/signup
Content-Type: application/json
{
    "username": "tasneem",
    "password": "123",

}



###
POST http://localhost:3001/signin
Content-Type: application/json
Authorization: 
{
    "username": "tam",
    "password": "1",
    "role": "admin"
}

###
POST http://localhost:3001/signin
Content-Type: application/json
Authorization: 


// {
 
  "name": "kfc",
   "type": "fast food",
   "order_path":111,
   "rating": "***",
   "delivery_fee":"2 jd"

# }



# {
    "username": "tas",
    "password": "1",
    "role": "user",
    "email": "xx@gmail.com",
    "phone": 792957765,
    "car_model": "ford"

# }
